CREATE OR REPLACE PACKAGE PAQUETE_FACTURAS AS
  -- Procedimientos
  PROCEDURE ALTA_FACTURA(COD_FACTURA IN NUMBER, FECHA IN DATE, DESCRIPCION IN VARCHAR2);

  PROCEDURE BAJA_FACTURA(cod_factura IN NUMBER);

  PROCEDURE MOD_DESCRI(COD_FACTURA IN NUMBER, DESCRIPCION IN VARCHAR2);

  PROCEDURE MOD_FECHA(COD_FACTURA IN NUMBER, FECHA IN DATE);

  -- Funciones
  FUNCTION NUM_FACTURAS(FECHA_INICIO IN DATE, FECHA_FIN IN DATE) RETURN NUMBER;

  FUNCTION TOTAL_FACTURA(COD_FACTURA IN NUMBER) RETURN NUMBER;
END PAQUETE_FACTURAS;
/

CREATE OR REPLACE PACKAGE BODY PAQUETE_FACTURAS AS
  -- Procedimiento para dar de alta una factura
  PROCEDURE ALTA_FACTURA(COD_FACTURA IN NUMBER, FECHA IN DATE, DESCRIPCION IN VARCHAR2) IS
  BEGIN
    -- Verificar si la factura ya existe
    IF EXISTS(SELECT 1 FROM HR.FACTURAS WHERE COD_FACTURA = COD_FACTURA) THEN
      DBMS_OUTPUT.PUT_LINE('La factura ya existe.');
    ELSE
      -- Insertar la factura en la tabla FACTURAS
      INSERT INTO HR.FACTURAS(COD_FACTURA, FECHA, DESCRIPCION)
      VALUES (COD_FACTURA, FECHA, DESCRIPCION);
      COMMIT;
      DBMS_OUTPUT.PUT_LINE('Factura creada exitosamente.');
    END IF;
  END ALTA_FACTURA;

  -- Procedimiento para borrar una factura y sus líneas asociadas
  PROCEDURE BAJA_FACTURA(COD_FACTURA IN NUMBER) IS
  BEGIN
    -- Borrar las líneas de factura asociadas en LINEAS_FACTURA
    DELETE FROM HR.LINEAS_FACTURA WHERE COD_FACTURA = COD_FACTURA;

    -- Borrar la factura en FACTURAS
    DELETE FROM HR.FACTURAS WHERE COD_FACTURA = COD_FACTURA;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Factura y líneas asociadas eliminadas.');
  END BAJA_FACTURA;

  -- Procedimiento para modificar la descripción de una factura
  PROCEDURE MOD_DESCRI(COD_FACTURA IN NUMBER, DESCRIPCION IN VARCHAR2) IS
  BEGIN
    -- Modificar la descripción en FACTURAS
    UPDATE HR.FACTURAS
    SET DESCRIPCION = DESCRIPCION
    WHERE COD_FACTURA = COD_FACTURA;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Descripción modificada exitosamente.');
  END MOD_DESCRI;

  -- Procedimiento para modificar la fecha de una factura
  PROCEDURE MOD_FECHA(COD_FACTURA IN NUMBER, FECHA IN DATE) IS
  BEGIN
    -- Modificar la fecha en FACTURAS
    UPDATE HR.FACTURAS
    SET FECHA = FECHA
    WHERE COD_FACTURA = COD_FACTURA;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Fecha modificada exitosamente.');
  END MOD_FECHA;

  -- Función para obtener el número de facturas entre dos fechas
  FUNCTION NUM_FACTURAS(FECHA_INICIO IN DATE, FECHA_FIN IN DATE) RETURN NUMBER IS
    NUM_FACT NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO NUM_FACT
    FROM HR.FACTURAS
    WHERE FECHA BETWEEN FECHA_INICIO AND FECHA_FIN;
    RETURN NUM_FACT;
  END NUM_FACTURAS;

  -- Función para obtener el total de una factura
  FUNCTION TOTAL_FACTURA(COD_FACTURA IN NUMBER) RETURN NUMBER IS
    TOTAL NUMBER;
  BEGIN
    SELECT SUM(PVP * UNIDADES)
    INTO TOTAL
    FROM HR.LINEAS_FACTURA
    WHERE COD_FACTURA = COD_FACTURA;
    RETURN TOTAL;
  END TOTAL_FACTURA;
END PAQUETE_FACTURAS;
/