CREATE OR REPLACE PACKAGE LINEAS_FACTURAS_PKG AS
  -- Procedimiento para insertar una línea de Factura
  PROCEDURE ALTA_LINEA(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER,
    UNIDADES IN NUMBER,
    FECHA IN DATE
  );

  -- Damos de baja la línea con esa clave primaria
  PROCEDURE BAJA_LINEA(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER
  );

  -- Modificar unidades o fecha
  PROCEDURE MOD_PRODUCTO(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER,
    UNIDADES IN NUMBER
  );

  PROCEDURE MOD_PRODUCTO(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER,
    FECHA IN DATE
  );

  -- Devuelve el número de líneas de la factura
  FUNCTION NUM_LINEAS(COD_FACTURA IN NUMBER) RETURN NUMBER;
END LINEAS_FACTURAS_PKG;
/

CREATE OR REPLACE PACKAGE BODY LINEAS_FACTURAS_PKG AS
  -- Procedimiento para insertar una línea de Factura
  PROCEDURE ALTA_LINEA(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER,
    UNIDADES IN NUMBER,
    FECHA IN DATE
  ) IS
  BEGIN
    -- Comprobar si la factura existe
    IF NOT EXISTS(SELECT 1 FROM FACTURAS WHERE COD_FACTURA = COD_FACTURA) THEN
      RAISE_APPLICATION_ERROR(-20001, 'La factura no existe');
    END IF;

    -- Comprobar si el producto existe
    IF NOT EXISTS(SELECT 1 FROM PRODUCTOS WHERE COD_PRODUCTO = COD_PRODUCTO) THEN
      RAISE_APPLICATION_ERROR(-20002, 'El producto no existe');
    END IF;

    -- Obtener el PVP del producto
    SELECT PVP INTO PVP FROM PRODUCTOS WHERE COD_PRODUCTO = COD_PRODUCTO;

    -- Insertar la línea de factura
    INSERT INTO LINEAS_FACTURA (COD_FACTURA, COD_PRODUCTO, PVP, UNIDADES, FECHA)
    VALUES (COD_FACTURA, COD_PRODUCTO, PVP, UNIDADES, FECHA);
  END ALTA_LINEA;

  -- Damos de baja la línea con esa clave primaria
  PROCEDURE BAJA_LINEA(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER
  ) IS
  BEGIN
    DELETE FROM LINEAS_FACTURA
    WHERE COD_FACTURA = COD_FACTURA AND COD_PRODUCTO = COD_PRODUCTO;
  END BAJA_LINEA;

  -- Modificar unidades
  PROCEDURE MOD_PRODUCTO(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER,
    UNIDADES IN NUMBER
  ) IS
  BEGIN
    UPDATE LINEAS_FACTURA
    SET UNIDADES = UNIDADES
    WHERE COD_FACTURA = COD_FACTURA AND COD_PRODUCTO = COD_PRODUCTO;
  END MOD_PRODUCTO;

  -- Modificar fecha
  PROCEDURE MOD_PRODUCTO(
    COD_FACTURA IN NUMBER,
    COD_PRODUCTO IN NUMBER,
    FECHA IN DATE
  ) IS
  BEGIN
    UPDATE LINEAS_FACTURA
    SET FECHA = FECHA
    WHERE COD_FACTURA = COD_FACTURA AND COD_PRODUCTO = COD_PRODUCTO;
  END MOD_PRODUCTO;

  -- Devuelve el número de líneas de la factura
  FUNCTION NUM_LINEAS(COD_FACTURA IN NUMBER) RETURN NUMBER IS
    NUM_LINES NUMBER;
  BEGIN
    SELECT COUNT(*) INTO NUM_LINES
    FROM LINEAS_FACTURA
    WHERE COD_FACTURA = COD_FACTURA;
    RETURN NUM_LINES;
  END NUM_LINEAS;
END LINEAS_FACTURAS_PKG;
/